### ISSUE TITLE
Credential Requirement

### ISSUE THREAD

**Issue by KZeronimo** [expertasolutions/AzureDNSZoneExtensions#17]
I would like to investigate the usage of this task - shouldn't it be feasible to utilize the service connection for authN/Z

That seems to be adequate for both the built Azure PS and AZ CLI tasks - having to provide an Azure username and pwd is a non-starter

Would be will to work with you on improving this (would be a learning for me) as well as add other capabilities when interacting with DNS (other record types)

**Comment by lturmel** [comment]
I've just made the change in Issue_00017 branch. The User/Pwd is now removed from the task.
I'm looking forward to release it in public marketplace

**Comment by lturmel** [comment]
The update with the removal of the Azure User/Pwd is now public on the marketplace..

Thanks a lot for you comment, and don't hesitate to contribute ;)
