### ISSUE TITLE
CName Alias not visible

### ISSUE THREAD

**Issue by drewkg** [expertasolutions/AzureDNSZoneExtensions#26]
Just installed the extensions, and trying to create / update a CName record, however the alias field is not visible in the release extension UI.

**Comment by expertasolutions** [comment]
hi Keith, ok thanks, I will look at it when I will be back

Louis Turmel
Solutions Experta Inc.
Tel: 1-514-447-8579 ext: 901
lturmel@expertasolutions.com
http://www.expertasolutions.com
Montreal, Canada

Sent from Outlook<https://aka.ms/qtex0l> on my iphone 6

________________________________

**Comment by lturmel** [comment]
Hi Keith, I found quickly the issue about the task related to the "ActionType" selection.
I'm fixing it right now and update the task package real soon.
Thanks,

**Comment by lturmel** [comment]
The defaultValue of ActionType parameters in the Task.json of "A" and "CName" is now fixed from the #27
